import javax.swing.*;


public class Main{
    public static void main (String[] args){

       Concert c = new Concert();
        c.setComp("FOLLOVE SEVENTEEN TOUR", "img/wa.jpg", "SEVENTEEN TOUR 'FOLLOW' is the third Asia tour by SEVENTEEN. The tour began on July 21, 2023 at the Gocheok Sky Dome in Seoul, South Korea.", "July 21, 2023 AT 9:00 PM", " Thailand");
        c.setComp("TAYLOR SWIFT THE 1989 WORLD TOUR", "img/1989.jpg","The 1989 World Tour was the fourth concert tour by the American singer-songwriter Taylor Swift, who embarked on it to support of her fifth studio album, 1989 (2014). Swift announced the tour's first dates in North America, Europe, Japan, and Oceania in November and December 2014. She announced additional dates for Singapore and China in June 2015, and a final announcement of the third show in Melbourne was made the following month.","May 15,2013 AT 7:30 PM","AsiaEuropeNorth AmericaOceania");
        c.setComp("THE FELLOWSHIP: BREAK THE WALL", "img/anch.jpg","On July 18, 2022, the group announced that they would be holding their second world tour of the year, The Fellowship : Break the Wall, with the release of the tour's poster.[2] the first venues were announced.[3] On December 1, they annouced the dates for the European leg.[4] On December 7, a second date was added in Paris.[5]","August 20, 2022 AT 6:00 PM","Seoul");
        c.setComp("4TH WORLD TOUR III  TWICE III", "img/bla.jpg","On October 1, 2021, an unnamed upcoming world tour was announced through the music video of \"The Feels\", the group's first English-language single.[2] The name of the tour, Twice 4th World Tour \"III\", was revealed on November 15, with the initial 8 tour dates being announced on the same day.[3] Additional concerts in Los Angeles and New York were added not long after due to overwhelming demand. On December 16, JYP Entertainment announced that the first concert in Seoul that was scheduled to take place on Christmas eve was canceled due to Covid-19 restrictions and venue operating hour restrictions.[4]","December 25, 2021 AT 7:00 PM","North America");
        c.setComp("Sweetener", "img/aria.jpg"," Grande finally hinted a tour via her official Twitter account,[4] shortly after announcing the title for her upcoming album on The Tonight Show Starring Jimmy Fallon.[5] Three months later, she announced that there were plans for a tour, stating that her team were \"workin [sic] on it all now\".[6] Grande embarked on a promotional concert tour for Sweetener"," May 6, 2018 AT 8:30 PM","New York City");
        c.setComp("ITZY 2ND WORLD TOUR BORN TO BE", "img/born.jpg","the group announced the tour's dates and venues. It was also announced that the second show in Seoul","January 26, 2024 AT 9:00 PM","Seoul");
        c.setComp("SPECIAL SUNDAY VINICIUS ZULATO", "img/ei.jpg","LIVE | VINICIUS ZULATO + LMC MUSIC | LAGOINHA MIAMI CHURCH. LAGOINHA MIAMI CHURCH · PAULO OLIVEIRA + LMC MUSIC | LAGOINHA MIAMI CHURCH.","11:00 AM", "Miami");
        c.setComp("THE SUPER SOWL 47TH HALF TIME SHOW BEYONCE", "img/for.jpg","news sources confirmed Beyoncé would headline the halftime show at the Super Bowl XLVII. Beyoncé made the announcement on her website prior to the National Football League's confirmation by posting an image of her face with the date of the game stenciled into eye black. Lisa de Moraes of The Washington Post quipped that she would become the first \"female solo artist under the age of AARP eligibility\" to headline the Super Bowl halftime show. Initial reports mentioned that Beyoncé's husband, Jay-Z was a potential collaborator on the show. However, he did not appear during the show, and a source told to Us Weekly that he changed his decision at the last minute as he wanted the performance \"to be her moment and didn't want to take away from it\".", "October 2012 AT 7:00 PM","New Orleans, Louisiana, United States");
        c.setComp("ARIANA GRANDE POSITIONS LIVE PERFORMANCES", "img/gran.jpg","Official Live Performance is a series of exclusive performances by American music video network Vevo, that aligns with artists \"providing fans with unique takes of original songs.","October 30, 2021 AT 8:00","Los Angeles, California");
        c.setComp("ITZY THE 1ST WORLD TOUR CHECKMATE D-DAY SEOUL", "img/mate.jpg"," ITZY announced their first world tour with a total of 10 dates in Seoul and the U.S. The poster contains the phrase \"and more\", suggesting that more dates will be added at a later date.[","August 8,2022 AT 6:00 PM","Seoul");
        c.setComp("LIVE MUSIC PERFORMANCE ", "img/nine.jpg"," live music performance in front of an audience.[1] The performance may be carried by a single musician, sometimes then called a recital, or by a musical ensemble, such as an orchestra, choir, or band. Concerts are held in a wide variety and size of settings, from private houses and small nightclubs, dedicated concert halls, amphitheatres and parks, to large multipurpose buildings, such as arenas and stadiums.","March 11,2023 AT 8:00 PM", "California USA");
        c.setComp("ROCK LIVE by: Thomas Bruix", "img/rock.jpg","performed several new album tracks in early 2015: \"Hold On Forever\", \"Great Unknown\", and \"Heaven Help Me\".[41] Thomas released the first single from The Great Unknown, \"Trust You\", on May 25, 2015. The Great Unknown was released on August 21, 2015. He spent two years touring it prior. \"Hold on Forever\" was announced as the album's second single on September 28.[45] The tour for Thomas' album included holographic representations of Thomas produced with vntana technology so that fans could pose for photos with him during the concert.","September 26,2023 AT 7:00 PM","New York");
        c.setComp("TAYLOR SWIFT THE ERAS TOUR", "img/sev.jpg","American concert film produced by the singer-songwriter Taylor Swift and directed by Sam Wrench. It documents the Los Angeles concerts of the Eras Tour (2023–2024), Swift's sixth headlining concert tour. Swift struck an unprecedented distribution agreement with AMC Theatres and Cinemark Theatres for the film after negotiations with the major film studios fell through.","August 2, 2023 AT 9:00 PM"," SoFi Stadium in Inglewood, California");
        c.setComp("ENHYPEN WORLD TOUR EATE", "img/six.jpg","ENHYPEN World Tour 'Fate' (stylized in all caps) is the second world tour by ENHYPEN. The first show was held with a two-night stint","July 29-30, 2023 AT 8:00 PM","Seoul, South Korea");
        c.setComp("TWICE 5TH WORLD TOUR READY TO BE SPECIAL", "img/sum.jpg","TWICE revealed that they would be holding a new world tour, TWICE 5th World Tour 'Ready To Be', with the announcement of part one of the tour. More shows will be announced at a later date."," February 22, 2023 AT 10:00 PM","Seoul");
        c.setComp("JUSTINE BIEBER AN INTERACTIVE VIRTUAL EXPERIENCE ", "img/ten.jpg","started teasing his musical comeback via his social media.[8] On December 20, Bieber tweeted that something was going to happen on the December 24, December 31, 2019, as well as on January 3 and 4, 2020. On December 24, he released a video on YouTube where he announced that he would release his fifth album during 2020","November 8,2020 AT 8:00 PM", "Texas");
        c.setComp("FRIDAY NIGHT PARTY ", "img/tres.jpg","Nightclubs generally restrict access to people in terms of age, attire, personal belongings, and inappropriate behaviors. Nightclubs typically have dress codes to prohibit people wearing informal, indecent, offensive, or gang-related attire from entering. Unlike other entertainment venues, nightclubs are more likely to use bouncers to screen prospective patrons for entry.","February 25,2024 AT 8:30 PM","Philippines");
        c.setComp("TWICE LIGHT THE WORLD TOUR", "img/twice.jpg","JYP Entertainment announced that due to the impact of the COVID-19 pandemic in South Korea, the final shows in Seoul were cancelled; it was followed by the announcement of the cancellation of the Tokyo shows two days later.","February 24,2019 AT 9:00 PM","Tokyo");
        c.setComp("BRUNO MARS", "img/uno.jpg","The last time Bruno Mars was in the country was for his 4K Magic World Tour","June 24, 2023 AT 9:30 PM","Philippine Arena Bulacan");




    }
}
